id: P004418
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17844
  title: བཀའ་པོད་ཆེན་པོ་ལྔའི་འཆད་ཉན་གྱི་གཡང་འབོད།
  author: ''
  volumes:
    11cf92eef3ee451e9c5dcb61aa7b1c95:
      image_group_id: I8LS17877
      title: ''
      volume_number: 1
      total_pages: 6
      base_file: v001.txt
