id: IC2BA9B49
legacy_id: P004418
ocr_import_info:
  bdrc_scan_id: W8LS17844
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T20:01:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:02:25.885328+00:00'
last_modified: 2022-09-04 12:02:30.119683
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17844
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17844
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་པོད་ཆེན་པོ་ལྔའི་འཆད་ཉན་གྱི་གཡང་འབོད།
  author: དཔའ་རིས་རབ་གསལ།
statistics:
  ocr_word_mean_confidence_index: 0.7810465146592537
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I8LS17877:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17877
      total_pages: 6
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17877.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.7810465146592537
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
